export type Role = "owner" | "admin" | "operator" | "viewer";
export type TenantContext = { tenantId: string; userId: string; roles: Role[] };
export type LeadStatus = "new" | "qualified" | "opportunity" | "won" | "lost";
export type Lead = { id: string; tenantId: string; name: string; email: string; company?: string; source: string; score: number; status: LeadStatus; createdAt: string };
export type Workflow = { id: string; tenantId: string; name: string; status: "draft" | "active" | "paused"; definition: Record<string, unknown>; version: number; updatedAt: string };
export type Agent = { id: string; tenantId: string; name: string; status: "idle" | "running" | "review"; model: string; tasksCompleted: number; updatedAt: string };
export type AuditEvent = { id: string; tenantId: string; actorId: string; action: string; resource: string; createdAt: string; metadata?: Record<string, unknown> };
export type UsageEvent = { id: string; tenantId: string; provider: string; model: string; inputTokens: number; outputTokens: number; estimatedCost: number; createdAt: string };
import { prismaClient } from "@/lib/prisma";
import { sessionContext } from "@/lib/auth";
const leads: Lead[] = []; const workflows: Workflow[] = [{ id: "wf-1", tenantId: "public-demo", name: "Purchase order review", status: "active", definition: { trigger: "purchase_order.created", steps: ["extract", "validate", "approve"] }, version: 1, updatedAt: new Date().toISOString() }]; const agents: Agent[] = [{ id: "agent-1", tenantId: "public-demo", name: "Procurement Copilot", status: "running", model: "gpt-4o-mini", tasksCompleted: 2481, updatedAt: new Date().toISOString() }, { id: "agent-2", tenantId: "public-demo", name: "Quality Inspector", status: "running", model: "azure-gpt-4o", tasksCompleted: 916, updatedAt: new Date().toISOString() }, { id: "agent-3", tenantId: "public-demo", name: "Maintenance Analyst", status: "review", model: "claude-sonnet", tasksCompleted: 308, updatedAt: new Date().toISOString() }]; const auditEvents: AuditEvent[] = []; const usageEvents: UsageEvent[] = [];
const rateBuckets = new Map<string, { count: number; resetAt: number }>();
export function getTenantContext(request: Request): TenantContext { const tenantId = request.headers.get("x-tenant-id") ?? "public-demo"; const userId = request.headers.get("x-user-id") ?? "anonymous"; const roles = (request.headers.get("x-roles") ?? "viewer").split(",").filter((role): role is Role => ["owner", "admin", "operator", "viewer"].includes(role)); return { tenantId, userId, roles: roles.length ? roles : ["viewer"] }; }
export function requireRole(context: TenantContext, allowed: Role[]) { if (!context.roles.some(role => allowed.includes(role))) throw new Error("FORBIDDEN"); }
export function enforceRateLimit(request: Request, limit = 60, windowMs = 60_000) { const key = request.headers.get("x-forwarded-for") ?? "local"; const now = Date.now(); const current = rateBuckets.get(key); if (!current || current.resetAt <= now) rateBuckets.set(key, { count: 1, resetAt: now + windowMs }); else { current.count += 1; if (current.count > limit) throw new Error("RATE_LIMITED"); } }
export function validateLead(input: unknown): Omit<Lead, "id" | "tenantId" | "score" | "status" | "createdAt"> { if (!input || typeof input !== "object") throw new Error("INVALID_INPUT"); const value = input as Record<string, unknown>; const name = typeof value.name === "string" ? value.name.trim() : ""; const email = typeof value.email === "string" ? value.email.trim().toLowerCase() : ""; const company = typeof value.company === "string" ? value.company.trim() : undefined; const source = typeof value.source === "string" ? value.source.trim() : "website"; if (name.length < 2 || !/^\S+@\S+\.\S+$/.test(email)) throw new Error("INVALID_INPUT"); return { name, email, company, source }; }
export function scoreLead(lead: Omit<Lead, "id" | "tenantId" | "score" | "status" | "createdAt">) { return Math.min(100, 20 + (lead.company ? 30 : 0) + (lead.email.endsWith(".de") || lead.email.endsWith(".eu") ? 25 : 10) + (lead.source === "referral" ? 25 : 10)); }
export async function createLead(context: TenantContext, input: unknown) { const data = validateLead(input); const client = await prismaClient(); if (client) { const tenant = await client.tenant.upsert({ where: { id: context.tenantId }, update: {}, create: { id: context.tenantId, name: context.tenantId, slug: context.tenantId } }); const lead = await client.lead.create({ data: { ...data, tenantId: tenant.id, score: scoreLead(data) } }); await createAuditEvent(context, "lead.created", `lead:${lead.id}`, { score: lead.score, source: lead.source }); return lead; } const lead: Lead = { ...data, id: crypto.randomUUID(), tenantId: context.tenantId, score: scoreLead(data), status: "new", createdAt: new Date().toISOString() }; leads.push(lead); await createAuditEvent(context, "lead.created", `lead:${lead.id}`, { score: lead.score, source: lead.source }); return lead; }
export async function listLeads(context: TenantContext) { const client = await prismaClient(); if (client) return client.lead.findMany({ where: { tenantId: context.tenantId }, orderBy: { createdAt: "desc" } }); return leads.filter(lead => lead.tenantId === context.tenantId); }
export async function listWorkflows(context: TenantContext) { const client = await prismaClient(); if (client) return client.workflow.findMany({ where: { tenantId: context.tenantId }, orderBy: { updatedAt: "desc" } }); return workflows.filter(workflow => workflow.tenantId === context.tenantId); }
export async function createWorkflow(context: TenantContext, input: unknown) { if (!input || typeof input !== "object") throw new Error("INVALID_INPUT"); const value = input as Record<string, unknown>; if (typeof value.name !== "string" || value.name.trim().length < 2) throw new Error("INVALID_INPUT"); const client = await prismaClient(); if (client) { await client.tenant.upsert({ where: { id: context.tenantId }, update: {}, create: { id: context.tenantId, name: context.tenantId, slug: context.tenantId } }); const workflow = await client.workflow.create({ data: { tenantId: context.tenantId, name: value.name.trim(), definition: typeof value.definition === "object" && value.definition ? value.definition as object : {} } }); await createAuditEvent(context, "workflow.created", `workflow:${workflow.id}`); return workflow; } const workflow: Workflow = { id: crypto.randomUUID(), tenantId: context.tenantId, name: value.name.trim(), status: "draft", definition: typeof value.definition === "object" && value.definition ? value.definition as Record<string, unknown> : {}, version: 1, updatedAt: new Date().toISOString() }; workflows.push(workflow); await createAuditEvent(context, "workflow.created", `workflow:${workflow.id}`); return workflow; }
export async function listAgents(context: TenantContext) { const client = await prismaClient(); if (client) return client.agent.findMany({ where: { tenantId: context.tenantId }, orderBy: { updatedAt: "desc" } }); return agents.filter(agent => agent.tenantId === context.tenantId); }
export async function createAuditEvent(context: TenantContext, action: string, resource: string, metadata?: Record<string, unknown>) { const client = await prismaClient(); if (client) { await client.tenant.upsert({ where: { id: context.tenantId }, update: {}, create: { id: context.tenantId, name: context.tenantId, slug: context.tenantId } }); return client.auditEvent.create({ data: { tenantId: context.tenantId, actorId: context.userId, action, resource, metadata: metadata ?? {} } }); } const event = { id: crypto.randomUUID(), tenantId: context.tenantId, actorId: context.userId, action, resource, createdAt: new Date().toISOString(), metadata }; auditEvents.push(event); return event; }
export async function listAuditEvents(context: TenantContext) { const client = await prismaClient(); if (client) return client.auditEvent.findMany({ where: { tenantId: context.tenantId }, orderBy: { createdAt: "desc" } }); return auditEvents.filter(event => event.tenantId === context.tenantId); }
export async function recordUsage(context: TenantContext, input: Omit<UsageEvent, "id" | "tenantId" | "createdAt">) { const event = { ...input, id: crypto.randomUUID(), tenantId: context.tenantId, createdAt: new Date().toISOString() }; usageEvents.push(event); return event; }
export async function listUsage(context: TenantContext) { return usageEvents.filter(event => event.tenantId === context.tenantId); }
